territory-data-loc: territory.csv
territory-limit: 15
guard-data-loc: guards.csv
relationship-data-loc: relationships.csv
glory-data-loc: glory.csv
glory-config:
  alliance-multiplier: -0.21
  war-multiplier: 0.37
  territory-hog-multiplier: 0.16
  starting-glory-amount: 0
  price:
    claim-territory: 750
    declare-war-min: 1000
    declare-war-max: 10000
    guard-spawn:
      patrol: 50
      brute: 1500
      ranger: 50
      hound: 2500
      bruiser: 500
  events:
    surrender-penalty: -5000
    war-victory: 6000
    kill-guard: 25
    kill-guard-brute: 100
    mob-kill: 10
    guard-execute-penalty: -100
    defense-kill: 75
    wild-kill: 150
    offensive-kill: 300
    territories-holding: 50
    defeat-penalty: -100
    environment-death-penalty: -450
    diamond-mining: 45
    guard-defense: 90