#https://bukkit.fandom.com/wiki/Plugin_YAML
name: HuntersMC
version: 1.0.0
main: com.gabler.huntersmc.HuntersMcPlugin
description: PvP plugin for managing territories and wars between territories.
authors:
  - AndyTheBrick
api-version: 1.18
commands:
  hunt:
    description: Reveal the location of another player and let them know you are tracking them.
    permission-message: Andy can't code so you don't have permission to this important command.
    usage: "Usage: /hunt <player name>"
  claim:
    description: Attempt to claim territory you are in.
    permission-message: Andy can't code so you don't have permission to this important command.
    usage: "Usage: /claim <territory name [if first time]>"
  guard:
    description: Spawn a guard to protect your territory.
    permission-message: Andy can't code so you don't have permission to this important command.
    usage: "Usage: /guard <type, see guardtypes command>"
  guardtypes:
    description: Display guard types and their details.
    permission-message: Andy can't code so you don't have permission to this important command.
    usage: "Usage: /guardtypes <page number>"
  hmcsave:
    description: Force a save of HuntersMC data.
    permission-message: You do not have permission to do this.
    usage: "Usage: /hmcsave"
    permission: huntersmc.forcesave
  hmcguardspawn:
    description: Ensure that all guards that are supposed to exist are spawned.
    permission-message: You do not have permission to do this.
    usage: "Usage /hmcguardspawn <id0> <id1> ... <id#>"
    permisison: huntersmc.respawn
  guardlist:
    description: Get list of all guards.
    permission-message: You do not have permission to do this. Consider /myguards
    usage: "Usage /guardlist <page number>"
    permission: huntersmc.metrics
  myguards:
    description: List out all guards you have on your territory.
    permission-message: Andy can't code so you don't have permission to this important command.
    usage: "Usage /myguards"
  envoy:
    description: Invite a player into your territory as an ambassador.
    permission-message: Andy can't code so you don't have permission to this important command.
    usage: "Usage /envoy <player name> <expiration time> <expiration units [Day, Hour, Minute]>"
  eject:
    description: Eject an ambassador from your territory.
    permission-message: Andy can't code so you don't have permission to this important command.
    usage: "Usage /eject <player name>"
  ally:
    description: Ally with another territory.
    permission-message: Andy can't code so you don't have permission to this important command.
    usage: "Usage /ally <territory name> <offer expiration time> <expiration units [Day, Hour, Minute]>"
  rejectalliance:
    description: Reject alliance with another territory.
    permission-message: Andy can't code so you don't have permission to this important command.
    usage: "Usage /rejectalliance <territory name>"
  breakalliance:
    description: Break alliance with another territory.
    permission-message: Andy can't code so you don't have permission to this important command.
    usage: "Usage /breakalliance <territory name>"
  declarewar:
    description: Declare war on another territory.
    permission-message: Andy can't code so you don't have permission to this important command.
    usage: "Usage /declarewar <territory name>"
  surrender:
    description: Surrender your war with another territory.
    permission-message: Andy can't code so you don't have permission to this important command.
    usage: "Usage /surrender <territory name>"
  terms:
    description: See the terms you are on with another territory.
    permission-message: Andy can't code so you don't have permission to this important command.
    usage: "Usage /terms <territory name [optional]>"
  glory:
    description: Check the amount of glory you have accumulated.
    permission-message: Andy can't code so you don't have permission to this important command.
    usage: "Usage /glory"
  gloryset:
    description: Set the glory of a player.
    permission-message: You do not have permission to do this.
    usage: "Usage /gloryset <player name> <glory amount>"
    permission: huntersmc.set-glory
  hmcconfigure:
    description: Configure HuntersMC plugin.
    permission-message: You do not have permission to do this.
    usage: "Usage /hmcconfigure <parameter name> <value>"
    permission: huntersmc.update-config
permissions:
  huntersmc.*:
    description: Catchall for the HuntersMC plugin.
    children:
      huntersmc.maintenance: true
      huntersmc.admin: true
  huntersmc.admin:
    description: Admin for the HuntersMC plugin.
    children:
      huntersmc.maintenance: true
      huntersmc.update-config: true
      huntersmc.ignore-territory-protect: true
      huntersmc.set-glory: true
  huntersmc.maintenance:
    description: Maintainence controls for the HuntersMC plugin.
    children:
      huntersmc.forcesave: true
      huntersmc.respawn: true
      huntersmc.metrics: true
  huntersmc.metrics:
    description: Metrics for the HuntersMC plugin.
  huntersmc.forcesave:
    description: Ability to forcesave HuntersMC data.
  huntersmc.guardrespawn:
    description: Ability to force respawns of all despawned guards.
  huntersmc.ignore-territory-protect:
    description: Ability to build on territories otherwise protected.
    children:
      huntersmc.ignore-territory-block-protect: true
      huntersmc.ignore-territory-container-protect: True
  huntersmc.ignore-territory-block-protect:
    description: Ability to build on territories otherwise protected.
  huntersmc.ignore-territory-container-protect:
    description: Ability to build on territories otherwise protected.
  huntersmc.update-config:
    description: Ability to update the configuration.
  huntersmc.set-glory:
    description: Ability to set glory of another player.