#https://bukkit.fandom.com/wiki/Plugin_YAML
name: HuntersMC
version: 0.1.0
main: com.gabler.huntersmc.HuntersMcPlugin
description: PvP plugin for managing territories and wars between territories.
authors:
  - AndyTheBrick
commands:
  hunt:
    description: Reveal the location of another player and let them know you are tracking them.
    permission-message: Andy can't code so you don't have permission to this important command.
    usage: "Usage: /hunt <player name>"
  claim:
    description: Attempt to claim territory you are in.
    permission-message: Andy can't code so you don't have permission to this important command.
    usage: "Usage: /claim <territory name [if first time]>"
  guard:
    description: Spawn a guard to protect your territory.
    permission-message: Andy can't code so you don't have permission to this important command.
    usage: "Usage: /guard <type, see guardtypes command>"
  guardtypes:
    description: Display guard types and their details.
    permission-message: Andy can't code so you don't have permission to this important command.
    usage: "Usage: /guardtypes <page number>"
  hmcsave:
    description: Force a save of HuntersMC data.
    permission-message: You do not have permission to do this.
    usage: "Usage: /hmcsave"
    permission: huntersmc.forcesave
  hmcguardspawn:
    description: Ensure that all guards that are supposed to exist are spawned.
    permission-message: You do not have permission to do this.
    usage: "Usage /hmcguardspawn <id0> <id1> ... <id#>"
    permisison: huntersmc.respawn
  guardlist:
    description: Get list of all guards.
    permission-message: You do not have permission to do this. Consider /myguards
    usage: "Usage /guardlist <page number>"
    permission: huntersmc.metrics
  myguards:
    description: List out all guards you have on your territory.
    permission-message: Andy can't code so you don't have permission to this important command.
    usage: "Usage /myguards"
  envoy:
    description: Invite a player into your territory as an ambassador.
    permission-message: Andy can't code so you don't have permission to this important command.
    usage: "Usage /envoy <player name> <expiration time> <expiration units [Day, Hour, Minute]>"
  eject:
    description: Eject an ambassador from your territory.
    permission-message: Andy can't code so you don't have permission to this important command.
    usage: "Usage /eject <player name>"
  ally:
    description: Ally with another territory.
    permission-message: Andy can't code so you don't have permission to this important command.
    usage: "Usage /ally <territory name> <offer expiration time> <expiration units [Day, Hour, Minute]>"
  rejectalliance:
    description: Reject alliance with another territory.
    permission-message: Andy can't code so you don't have permission to this important command.
    usage: "Usage /rejectalliance <territory name>"
  breakalliance:
    description: Break alliance with another territory.
    permission-message: Andy can't code so you don't have permission to this important command.
    usage: "Usage /breakalliance <territory name>"
  declarewar:
    description: Declare war on another territory.
    permission-message: Andy can't code so you don't have permission to this important command.
    usage: "Usage /declarewar <territory name>"
  surrender:
    description: Surrender your war with another territory.
    permission-message: Andy can't code so you don't have permission to this important command.
    usage: "Usage /surrender <territory name>"
  terms:
    description: See the terms you are on with another territory.
    permission-message: Andy can't code so you don't have permission to this important command.
    usage: "Usage /terms <territory name [optional]>"
permissions:
  huntersmc.*:
    description: Catchall for the HuntersMC plugin.
    children:
      huntersmc.maintainence: true
  huntersmc.maintainence:
    description: Maintainence controls for the HuntersMC plugin.
    children:
      huntersmc.forcesave: true
      huntersmc.respawn: true
      huntersmc.metrics: true
  huntersmc.metrics:
    description: Metrics for the HuntersMC plugin.
  huntersmc.forcesave:
    description: Ability to forcesave HuntersMC data.
  huntersmc.guardrespawn:
    description: Ability to force respawns of all despawned guards.